<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;

class PhpPgDumper
{
    private \PDO $pdo;

    public function dumpToFile(string $path): ?string
    {
        $fh = @fopen($path, 'w');

        if ($fh === false) {
            return 'Не удалось создать файл: ' . $path;
        }

        try {
            $this->pdo = DB::getPdo();
            $this->writeDump($fh);
        } catch (\Throwable $e) {
            fclose($fh);
            @unlink($path);

            return $e->getMessage();
        }

        fclose($fh);

        return null;
    }

    private function writeDump($fh): void
    {
        $this->w($fh, "--\n-- PostgreSQL database dump\n-- Generated by Zentra CMF · " . date('Y-m-d H:i:s T') . "\n--\n\n");
        $this->w($fh, "SET client_encoding = 'UTF8';\n");
        $this->w($fh, "SET standard_conforming_strings = on;\n");
        $this->w($fh, "SET check_function_bodies = false;\n");
        $this->w($fh, "SET client_min_messages = warning;\n");
        $this->w($fh, "SET row_security = off;\n\n");

        $tables = $this->getPublicTables();
        $sequences = $this->getSequences();

        foreach ($tables as $table) {
            $this->w($fh, "DROP TABLE IF EXISTS public.\"$table\" CASCADE;\n");
        }

        foreach ($sequences as $seq) {
            $this->w($fh, "DROP SEQUENCE IF EXISTS public.\"{$seq->sequence_name}\" CASCADE;\n");
        }

        $this->w($fh, "\n");

        foreach ($sequences as $seq) {
            $this->writeSequence($fh, $seq);
        }

        foreach ($tables as $table) {
            $this->writeTableDDL($fh, $table);
        }

        foreach ($tables as $table) {
            $this->writeTableData($fh, $table);
        }

        foreach ($tables as $table) {
            foreach ($this->getConstraints($table, ['p', 'u', 'c']) as $c) {
                $this->w($fh, "ALTER TABLE ONLY public.\"$table\"\n    ADD CONSTRAINT \"{$c->conname}\" {$c->constraintdef};\n\n");
            }
        }

        foreach ($tables as $table) {
            foreach ($this->getIndexes($table) as $idx) {
                $this->w($fh, $idx->indexdef . ";\n");
            }
        }
        $this->w($fh, "\n");

        foreach ($tables as $table) {
            foreach ($this->getConstraints($table, ['f']) as $c) {
                $this->w($fh, "ALTER TABLE ONLY public.\"$table\"\n    ADD CONSTRAINT \"{$c->conname}\" {$c->constraintdef};\n\n");
            }
        }

        foreach ($sequences as $seq) {
            $val = $this->getSequenceValue($seq->sequence_name);

            if ($val !== null) {
                $name = str_replace("'", "''", $seq->sequence_name);
                $this->w($fh, "SELECT pg_catalog.setval('public.$name', $val, true);\n");
            }
        }

        $this->w($fh, "\n-- PostgreSQL database dump complete\n");
    }

    private function writeSequence($fh, object $seq): void
    {
        $cycle = $seq->cycle_option === 'YES' ? 'CYCLE' : 'NO CYCLE';
        $this->w($fh, implode("\n", [
            "CREATE SEQUENCE public.{$seq->sequence_name}",
            "    AS {$seq->data_type}",
            "    START WITH {$seq->start_value}",
            "    INCREMENT BY {$seq->increment}",
            "    MINVALUE {$seq->minimum_value}",
            "    MAXVALUE {$seq->maximum_value}",
            '    CACHE 1',
            "    $cycle;",
        ]) . "\n\n");
    }

    private function writeTableDDL($fh, string $table): void
    {
        $cols = DB::select("
            SELECT a.attname                                AS name,
                   format_type(a.atttypid, a.atttypmod)   AS type,
                   a.attnotnull                            AS not_null,
                   pg_get_expr(d.adbin, d.adrelid)        AS default_val
            FROM   pg_attribute   a
            JOIN   pg_class       c ON c.oid = a.attrelid
            JOIN   pg_namespace   n ON n.oid = c.relnamespace
            LEFT   JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
            WHERE  n.nspname = 'public' AND c.relname = ?
               AND a.attnum > 0 AND NOT a.attisdropped
            ORDER  BY a.attnum
        ", [$table]);

        if (empty($cols)) {
            return;
        }

        $this->w($fh, "CREATE TABLE public.\"$table\" (\n");
        $last = count($cols) - 1;

        foreach ($cols as $i => $col) {
            $line = "    \"{$col->name}\" {$col->type}";

            if ($col->default_val !== null) {
                $line .= " DEFAULT {$col->default_val}";
            }

            if ($col->not_null) {
                $line .= ' NOT NULL';
            }

            $this->w($fh, $line . ($i < $last ? ',' : '') . "\n");
        }

        $this->w($fh, ");\n\n");
    }

    private function writeTableData($fh, string $table): void
    {
        $safe = str_replace('"', '', $table);
        $stmt = $this->pdo->query("SELECT * FROM public.\"$safe\"");

        if (!$stmt) {
            return;
        }

        $cols = null;
        $hasData = false;

        while ($row = $stmt->fetch(\PDO::FETCH_ASSOC)) {
            if ($cols === null) {
                $cols = implode(', ', array_map(fn ($c) => '"' . $c . '"', array_keys($row)));
                $hasData = true;
                $this->w($fh, "-- Data: $table\n");
            }

            $vals = implode(', ', array_map(fn ($v) => $this->q($v), $row));
            $this->w($fh, "INSERT INTO public.\"$safe\" ($cols) VALUES ($vals);\n");
        }

        if ($hasData) {
            $this->w($fh, "\n");
        }
    }

    private function getConstraints(string $table, array $types): array
    {
        $ph = implode(',', array_fill(0, count($types), '?'));

        return DB::select(
            "SELECT c.conname, pg_get_constraintdef(c.oid) AS constraintdef
             FROM   pg_constraint c
             JOIN   pg_class t ON t.oid = c.conrelid
             JOIN   pg_namespace n ON n.oid = t.relnamespace
             WHERE  n.nspname = 'public' AND t.relname = ? AND c.contype IN ($ph)
             ORDER  BY c.conname",
            array_merge([$table], $types),
        );
    }

    private function getIndexes(string $table): array
    {
        return DB::select("
            SELECT pg_get_indexdef(i.indexrelid) AS indexdef
            FROM   pg_index i
            JOIN   pg_class c ON c.oid = i.indrelid
            JOIN   pg_namespace n ON n.oid = c.relnamespace
            WHERE  n.nspname = 'public' AND c.relname = ?
               AND NOT i.indisprimary
               AND NOT EXISTS (
                   SELECT 1 FROM pg_constraint con
                   WHERE  con.conrelid = c.oid AND con.conindid = i.indexrelid
                      AND con.contype IN ('u', 'p')
               )
        ", [$table]);
    }

    private function getPublicTables(): array
    {
        return array_column(DB::select("
            SELECT table_name
            FROM   information_schema.tables
            WHERE  table_schema = 'public' AND table_type = 'BASE TABLE'
            ORDER  BY table_name
        "), 'table_name');
    }

    private function getSequences(): array
    {
        return DB::select("
            SELECT sequence_name, data_type, start_value, minimum_value,
                   maximum_value, increment, cycle_option
            FROM   information_schema.sequences
            WHERE  sequence_schema = 'public'
            ORDER  BY sequence_name
        ");
    }

    private function getSequenceValue(string $name): ?int
    {
        try {
            $safe = str_replace('"', '', $name);
            $row = DB::selectOne("SELECT last_value, is_called FROM public.\"$safe\"");

            return ($row && $row->is_called) ? (int) $row->last_value : null;
        } catch (\Throwable) {
            return null;
        }
    }

    private function q(mixed $v): string
    {
        if ($v === null) {
            return 'NULL';
        }

        return $this->pdo->quote((string) $v);
    }

    private function w($fh, string $s): void
    {
        fwrite($fh, $s);
    }
}
