blank_issues_enabled: false
contact_links:
  - name: Вопрос по использованию
    url: https://github.com/zentra-team/zentra-cmf/discussions
    about: Если у вас вопрос по настройке или использованию — задайте его в Discussions
